# Generated by Django 2.2.5 on 2019-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
