# Generated by Django 2.2.5 on 2019-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('N', 'New'), ('I', 'In Progress'), ('C', 'Completed')], default='N', max_length=1),
        ),
    ]
