# Generated by Django 2.2.5 on 2019-09-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190917_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='about',
            new_name='user',
        ),
    ]
