# Generated by Django 2.2.5 on 2019-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190917_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('L', 'Low Importance'), ('M', 'Medium Importance'), ('H', 'High Importance')], default='L', max_length=1),
        ),
    ]
