# Generated by Django 2.2.5 on 2019-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
