# Generated by Django 2.2.5 on 2019-09-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190917_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=50)),
                ('dinner', models.CharField(max_length=50)),
                ('importance', models.CharField(choices=[('1', 'Low Importance'), ('3', 'Medium Importance'), ('5', 'High Importance')], default='Low Importance', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=250)),
                ('importance', models.CharField(choices=[('1', 'Low Importance'), ('3', 'Medium Importance'), ('5', 'High Importance')], default='Low Importance', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default='1', max_length=1),
        ),
    ]
