# Generated by Django 2.2.5 on 2019-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190917_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='post',
            name='inprogresstasks',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='assignedworkout',
            field=models.ManyToManyField(related_name='assignedWorkout', to='main_app.Workout'),
        ),
        migrations.AddField(
            model_name='post',
            name='completedworkout',
            field=models.ManyToManyField(related_name='completedWorkout', to='main_app.Workout'),
        ),
    ]
