# Generated by Django 2.2.5 on 2019-09-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190917_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mealplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.MealPlan'),
            preserve_default=False,
        ),
    ]
