# Generated by Django 2.2.5 on 2019-09-18 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190917_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('1', 'Low Importance'), ('3', 'Medium Importance'), ('5', 'High Importance')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='importance',
            field=models.CharField(choices=[('1', 'Low Importance'), ('3', 'Medium Importance'), ('5', 'High Importance')], default='3', max_length=1),
        ),
        migrations.RenameModel(
            old_name='Journal',
            new_name='Planner',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='entry',
            name='assignedtasks',
            field=models.ManyToManyField(related_name='assignedTasks', to='main_app.Task'),
        ),
        migrations.AddField(
            model_name='entry',
            name='assignedworkout',
            field=models.ManyToManyField(related_name='assignedWorkout', to='main_app.Workout'),
        ),
        migrations.AddField(
            model_name='entry',
            name='completedtasks',
            field=models.ManyToManyField(related_name='completedTasks', to='main_app.Task'),
        ),
        migrations.AddField(
            model_name='entry',
            name='completedworkout',
            field=models.ManyToManyField(related_name='completedWorkout', to='main_app.Workout'),
        ),
        migrations.AddField(
            model_name='entry',
            name='mealplan',
            field=models.ManyToManyField(to='main_app.MealPlan'),
        ),
        migrations.AddField(
            model_name='entry',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Planner'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Entry'),
            preserve_default=False,
        ),
    ]
