# Generated by Django 2.2.5 on 2019-09-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190917_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='assignedworkout',
            new_name='assignedworkouts',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='completedworkout',
            new_name='completedworkouts',
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
