# Generated by Django 2.2.5 on 2019-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20190918_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
