# Generated by Django 2.2.5 on 2019-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_entry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='Peasant', max_length=100),
        ),
    ]
