# Generated by Django 2.2.5 on 2019-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190919_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=1),
        ),
    ]
