# Generated by Django 2.2.5 on 2019-09-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190919_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurring',
        ),
    ]
